/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: c437fab4d4305dbff25621147457223f)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	INGEST_QUEUE: Queue;
	API_RATE_LIMITER: RateLimit;
	SEARCH_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
	PUBLISH_RATE_LIMITER: RateLimit;
	PUBLIC_SITE_URL: string;
	ENVIRONMENT: string;
	ADMIN_EMAILS: string;
	BETTER_AUTH_SECRET: string;
	INDEX_WORKFLOW: Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs-staging */ | Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs */ | Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs-local */;
}
declare namespace Cloudflare {
	interface StagingEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		INGEST_QUEUE: Queue;
		API_RATE_LIMITER: RateLimit;
		SEARCH_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		PUBLISH_RATE_LIMITER: RateLimit;
		PUBLIC_SITE_URL: string;
		ENVIRONMENT: string;
		ADMIN_EMAILS: string;
		BETTER_AUTH_SECRET: string;
		INDEX_WORKFLOW: Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs-staging */;
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		INGEST_QUEUE: Queue;
		API_RATE_LIMITER: RateLimit;
		SEARCH_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		PUBLISH_RATE_LIMITER: RateLimit;
		PUBLIC_SITE_URL: string;
		ENVIRONMENT: string;
		ADMIN_EMAILS: string;
		BETTER_AUTH_SECRET: string;
		INDEX_WORKFLOW: Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_URL" | "ENVIRONMENT" | "ADMIN_EMAILS" | "BETTER_AUTH_SECRET">> {}
}
