/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 68cde47bf999c770e6bdb68e6318c3d4)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	INGEST_QUEUE: Queue;
	PUBLIC_SITE_URL: string;
	ENVIRONMENT: string;
	ADMIN_EMAILS: string;
	INDEX_WORKFLOW: Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs-staging */ | Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs */ | Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs-local */;
}
declare namespace Cloudflare {
	interface StagingEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		INGEST_QUEUE: Queue;
		PUBLIC_SITE_URL: string;
		ENVIRONMENT: string;
		ADMIN_EMAILS: string;
		INDEX_WORKFLOW: Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs-staging */;
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		INGEST_QUEUE: Queue;
		PUBLIC_SITE_URL: string;
		ENVIRONMENT: string;
		ADMIN_EMAILS: string;
		INDEX_WORKFLOW: Workflow /* IndexPackageWorkflow from clarkcant-marketplace-jobs */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_URL" | "ENVIRONMENT" | "ADMIN_EMAILS">> {}
}
