import js from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import globals from "globals";
import tseslint from "typescript-eslint";

export default defineConfig([
  globalIgnores([
    "**/node_modules/",
    "**/dist/",
    "**/.astro/",
    "**/.wrangler/",
    "**/worker-configuration.d.ts",
    // Generated by the Better Auth CLI (`pnpm --filter @marketplace/db auth:schema`); regenerate, do not hand-edit.
    "packages/db/src/schema/auth.ts",
    "migrations/",
    "playwright-report/",
    "test-results/",
    "plans/",
  ]),
  {
    files: ["**/*.{js,mjs,cjs,ts,tsx}"],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      "@typescript-eslint/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "error",
      eqeqeq: ["error", "always"],
      "no-console": ["error", { allow: ["info", "warn", "error"] }],
    },
  },
  {
    files: ["scripts/**/*.mjs", "e2e/**/*.ts", "*.config.{js,ts}"],
    rules: { "no-console": "off" },
  },
  {
    // Ambient declaration files must stay scripts (no top-level import), so `import()` types are required there.
    files: ["**/*.d.ts"],
    rules: { "@typescript-eslint/consistent-type-imports": "off" },
  },
]);
