/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 383e8639c6c600602fedee4700592dad)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	INGEST_QUEUE: Queue;
	PUBLIC_SITE_URL: string;
	ENVIRONMENT: string;
	ADMIN_EMAILS: string;
	INDEX_WORKFLOW: Workflow<Parameters<import("./src/index").IndexPackageWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		INGEST_QUEUE: Queue;
		PUBLIC_SITE_URL: string;
		ENVIRONMENT: string;
		ADMIN_EMAILS: string;
		INDEX_WORKFLOW: Workflow<Parameters<import("./src/index").IndexPackageWorkflow['run']>[0]['payload']>;
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		INGEST_QUEUE: Queue;
		PUBLIC_SITE_URL: string;
		ENVIRONMENT: string;
		ADMIN_EMAILS: string;
		INDEX_WORKFLOW: Workflow<Parameters<import("./src/index").IndexPackageWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_URL" | "ENVIRONMENT" | "ADMIN_EMAILS">> {}
}
