/**
 * Regenerates the SDK's TypeScript types (`src/generated/openapi.ts`) from the API package's route definitions,
 * in-process. Run `pnpm --filter @marketplace/sdk openapi:generate` after any change to an `/api/v1` route; the SDK
 * test suite compares the recorded document digest with the live document and fails while the types are stale.
 */
import { writeFile } from "node:fs/promises";

import { createApi } from "@marketplace/api";
import { MarketplaceError } from "@marketplace/contracts";
import openapiTS, { astToString } from "openapi-typescript";

import { normalizeOpenApiDocument, openApiDigest } from "../src/openapi-snapshot";

const api = createApi({
  resolveContext: () => {
    throw new MarketplaceError("configuration_error", "the OpenAPI generator serves no /api/v1 requests");
  },
});
const response = await api.request("http://localhost/openapi.json");
if (response.status !== 200) throw new Error(`openapi.json answered ${response.status}`);
const document = normalizeOpenApiDocument(await response.json());

const ast = await openapiTS(document as Parameters<typeof openapiTS>[0], { alphabetize: true });
const source =
  "/* eslint-disable */\n" +
  "// Generated by `pnpm --filter @marketplace/sdk openapi:generate` from the API's OpenAPI document. Do not edit.\n\n" +
  astToString(ast) +
  `\n/** SHA-256 of the OpenAPI document these types were generated from (without \`servers\`). */\n` +
  `export const OPENAPI_DOCUMENT_SHA256 = "${await openApiDigest(document)}";\n`;
await writeFile(new URL("../src/generated/openapi.ts", import.meta.url), source);
console.info("wrote packages/sdk/src/generated/openapi.ts");
