import type { APIRoute } from "astro";

import { api } from "../server/api";

export const prerender = false;

/** The OpenAPI 3.1 document is generated by the API package from the same route definitions it serves. */
export const GET: APIRoute = ({ request, locals }) => api.fetch(request, undefined, locals.cfContext);
